language: java

jdk:
  - openjdk11

script:
  - java -jar "$TRAVIS_BUILD_DIR"/sorald/target/sorald-1.1-SNAPSHOT-jar-with-dependencies.jar --originalFilesPath "$TRAVIS_BUILD_DIR"/sorald/src/test/resources/ArrayHashCodeAndToString.java --ruleKeys 2184
  - mvn spotless:check test

after_success: bash <(curl -s https://codecov.io/bash)
