language: java

jdk:
  - openjdk10

script:
  - java -jar /home/travis/build/fermadeiral/sonarqube-repair/target/sonarqube-repair-1.1-SNAPSHOT-jar-with-dependencies.jar --originalFilesPath /home/travis/build/fermadeiral/sonarqube-repair/src/test/resources/ArrayHashCodeAndToString.java --ruleKeys 2184
