language: java

jdk:
  - openjdk8

script:
  - java -jar /home/travis/build/SpoonLabs/sonarqube-repair/target/sonarqube-repair-1.1-SNAPSHOT-jar-with-dependencies.jar to /home/travis/.m2/repository/se/kth/castor/sonarqube-repair/1.1-SNAPSHOT/sonarqube-repair-1.1-SNAPSHOT-jar-with-dependencies.jar --originalFilesPath /home/travis/build/SpoonLabs/sonarqube-repair/src/test/resources/ArrayHashCodeAndToString.java --ruleKeys 2116
