codecov:
  require_ci_to_pass: no

comment: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
      project: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
