name: combine-prs

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v4.1.0
        with:
          branch_prefix: 'combine-prs'
          pr_title: 'chore: combine renovate[bot] PRs'
          branch_regex: '^renovate/.*'
