name: Lockfile
on:
  pull_request:

jobs:
  check-lockfile:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repository
          uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
          with:
            fetch-depth: 0
            ref: ${{ github.event.pull_request.head.ref }}
            repository: ${{github.event.pull_request.head.repo.full_name}}
        - name: Set up Maven
          uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
          with:
            maven-version: 3.8.2
        - name: run maven-lockfile
          uses: chains-project/maven-lockfile@v1.1.11
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
